# Generated by Django 4.0.1 on 2023-07-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='is_deleted',
        ),
    ]
