# Generated by Django 4.0.1 on 2023-07-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goalcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalcomment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
